team_map = {
    "Boston Red Stockings": "BS1",
    "Chicago White Stockings": "CH1",
    "Cleveland Forest Citys": "CL1",
    "Fort Wayne Kekiongas": "FW1",
    "New York Mutuals": "NY2",
    "Philadelphia Athletics": "PH1",
    "Rockford Forest Citys": "RC1",
    "Troy Haymakers": "TRO",
    "Washington Olympics": "WS3",
    "Baltimore Canaries": "BL1",
    "Brooklyn Eckfords": "BR1",
    "Brooklyn Atlantics": "BR2",
    "Middletown Mansfields": "MID",
    "Washington Nationals": "WS4",
    "Baltimore Marylands": "BL4",
    "Elizabeth Resolutes": "ELI",
    "Philadelphia Whites": "PH2",
    "Washington Blue Legs": "WS5",
    "Chicago White Stockings": "CH2",
    "Hartford Dark Blues": "HR1",
    "Keokuk Westerns": "KEO",
    "New Haven Elm Citys": "NH1",
    "Philadelphia Centennials": "PH3",
    "St. Louis Red Stockings": "SL1",
    "St. Louis Brown Stockings": "SL2",
    "Washington Nationals": "WS6",
    "Boston Red Caps": "BSN",
    "Chicago White Stockings": "CHN",
    "Cincinnati Reds": "CN1",
    "Hartford Dark Blues": "HAR",
    "Louisville Grays": "LS1",
    "New York Mutuals": "NY3",
    "Philadelphia Athletics": "PHN",
    "St. Louis Brown Stockings": "SL3",
    "Indianapolis Blues": "IN1",
    "Milwaukee Grays": "ML2",
    "Providence Grays": "PRO",
    "Buffalo Bisons": "BFN",
    "Cleveland Blues": "CL2",
    "Syracuse Stars": "SR1",
    "Troy Trojans": "TRN",
    "Worcester Ruby Legs": "WOR",
    "Detroit Wolverines": "DTN",
    "Baltimore Orioles": "BL2",
    "Cincinnati Red Stockings": "CN2",
    "Louisville Eclipse": "LS2",
    "Philadelphia Athletics": "PH4",
    "Pittsburg Alleghenys": "PT1",
    "St. Louis Brown Stockings": "SL4",
    "Boston Beaneaters": "BSN",
    "Columbus Buckeyes": "CL5",
    "New York Gothams": "NY1",
    "New York Metropolitans": "NY4",
    "Philadelphia Quakers": "PHI",
    "St. Louis Browns": "SL4",
    "Altoona Mountain City": "ALT",
    "Baltimore Monumentals": "BLU",
    "Brooklyn Atlantics": "BR3",
    "Boston Reds": "BSU",
    "Chicago/Pittsburgh (Union League)": "CHU",
    "Cincinnati Outlaw Reds": "CNU",
    "Indianapolis Hoosiers": "IN2",
    "Kansas City Cowboys": "KCU",
    "Milwaukee Brewers": "MLU",
    "Philadelphia Keystones": "PHU",
    "Richmond Virginians": "RIC",
    "St. Louis Maroons": "SLU",
    "St. Paul White Caps": "SPU",
    "Toledo Blue Stockings": "TL1",
    "Wilmington Quicksteps": "WIL",
    "Washington Nationals": "WS7",
    "Washington Nationals": "WSU",
    "Brooklyn Grays": "BR3",
    "Louisville Colonels": "LS2",
    "New York Giants": "NY1",
    "St. Louis Maroons": "SL5",
    "Kansas City Cowboys": "KCN",
    "Washington Nationals": "WS8",
    "Cleveland Blues": "CL3",
    "Indianapolis Hoosiers": "IN3",
    "Pittsburg Alleghenys": "PIT",
    "Brooklyn Bridegrooms": "BR3",
    "Kansas City Cowboys": "KC2",
    "Cleveland Spiders": "CL4",
    "Columbus Solons": "CL6",
    "Buffalo Bisons": "BFP",
    "Baltimore Orioles": "BL3",
    "Brooklyn Gladiators": "BR4",
    "Brooklyn Bridegrooms": "BRO",
    "Brooklyn Ward's Wonders": "BRP",
    "Boston Reds": "BSP",
    "Chicago Colts": "CHN",
    "Chicago Pirates": "CHP",
    "Cincinnati Reds": "CIN",
    "Cleveland Infants": "CLP",
    "New York Giants": "NYP",
    "Philadelphia Phillies": "PHI",
    "Philadelphia Athletics": "PHP",
    "Pittsburgh Burghers": "PTP",
    "Rochester Broncos": "RC2",
    "Syracuse Stars": "SR2",
    "Toledo Maumees": "TL2",
    "Brooklyn Grooms": "BRO",
    "Boston Reds": "BS2",
    "Cincinnati Kelly's Killers": "CN3",
    "Milwaukee Brewers": "ML3",
    "Pittsburgh Pirates": "PIT",
    "Washington Statesmen": "WS9",
    "Baltimore Orioles": "BLN",
    "Louisville Colonels": "LS3",
    "St. Louis Browns": "SLN",
    "Washington Senators": "WAS",
    "Chicago Orphans": "CHN",
    "Brooklyn Superbas": "BRO",
    "St. Louis Perfectos": "SLN",
    "St. Louis Cardinals": "SLN",
    "Baltimore Orioles": "BLA",
    "Boston Americans": "BOS",
    "Chicago White Sox": "CHA",
    "Cleveland Blues": "CLE",
    "Detroit Tigers": "DET",
    "Milwaukee Brewers": "MLA",
    "Philadelphia Athletics": "PHA",
    "Washington Senators": "WS1",
    "Cleveland Bronchos": "CLE",
    "St. Louis Browns": "SLA",
    "Chicago Cubs": "CHN",
    "Cleveland Naps": "CLE",
    "New York Highlanders": "NYA",
    "Boston Doves": "BSN",
    "Boston Red Sox": "BOS",
    "Brooklyn Dodgers": "BRO",
    "Boston Rustlers": "BSN",
    "Boston Braves": "BSN",
    "New York Yankees": "NYA",
    "Baltimore Terrapins": "BLF",
    "Brooklyn Tip-Tops": "BRF",
    "Brooklyn Robins": "BRO",
    "Buffalo Buffeds": "BUF",
    "Chicago Chi-Feds": "CHF",
    "Indianapolis Hoosiers": "IND",
    "Kansas City Packers": "KCF",
    "Pittsburgh Rebels": "PTF",
    "St. Louis Terriers": "SLF",
    "Buffalo Blues": "BUF",
    "Chicago Whales": "CHF",
    "Cleveland Indians": "CLE",
    "Newark Pepper": "NEW",
    "Boston Bees": "BSN",
    "Philadelphia Blue Jays": "PHI",
    "Milwaukee Braves": "ML1",
    "Baltimore Orioles": "BAL",
    "Cincinnati Redlegs": "CIN",
    "Kansas City Athletics": "KC1",
    "Los Angeles Dodgers": "LAN",
    "San Francisco Giants": "SFN",
    "Los Angeles Angels": "LAA",
    "Minnesota Twins": "MIN",
    "Washington Senators": "WS2",
    "Houston Colt .45's": "HOU",
    "New York Mets": "NYN",
    "California Angels": "CAL",
    "Houston Astros": "HOU",
    "Atlanta Braves": "ATL",
    "Oakland Athletics": "OAK",
    "Kansas City Royals": "KCA",
    "Montreal Expos": "MON",
    "San Diego Padres": "SDN",
    "Seattle Pilots": "SE1",
    "Milwaukee Brewers": "ML4",
    "Texas Rangers": "TEX",
    "Seattle Mariners": "SEA",
    "Toronto Blue Jays": "TOR",
    "Colorado Rockies": "COL",
    "Florida Marlins": "FLO",
    "Anaheim Angels": "ANA",
    "Arizona Diamondbacks": "ARI",
    "Milwaukee Brewers": "MIL",
    "Tampa Bay Devil Rays": "TBA",
    "Los Angeles Angels of Anaheim": "LAA",
    "Washington Nationals": "WAS",
    "Tampa Bay Rays": "TBA",
    "Miami Marlins": "MIA",
    "Cleveland Guardians": "CLE"
}